BackEnd/citas/urls.py
from django.urls import path
from .views import index,registrar_paciente, registrar_medico, login_medico, login_paciente ,dashboard_medico, dashboard_paciente, logout_user, crear_alergia, crear_especialidad, asignar_especialidad, listar_medicos, detalle_medico, listar_enfermedades_alergias, crear_enfermedad, listar_tratamientos, crear_tratamiento, asignar_tratamiento, listar_enfermedades_tratamientos, agregar_producto, listar_productos, crear_cita, listar_citas
from .views import login_usuario, register, inicio, listar_alergias, buscar_medicos, buscar_pacientes, obtener_especialidades, buscar_cita, crear_registro, buscar_enfermedades, tratamientos_por_enfermedad, paciente_citas,paciente_historial,paciente_inicio, editar_cita,registrar_paciente, vista_error, forgot_password_medico, validate_otp, change_password, validar_disponibilidad_medico

from .views import send_reminder, todas_las_citas_json, generar_reporte, historial_paciente, tipo_citas_all, cantidad_total_citas, visualizacion, citas_asistio, citas_no_asistio, citas_pendientes, filtro_enfermedades, filtrar_registros_tratamientos, citas_visualizacion, doctores_all, enfermedades_cantidad_pacientes, buscar_enfermedades, buscar_pacientes2, buscar_enfermedades, datos_tendencias_enfermedades, estadisticas_tratamientos, enfermedades_por_tratamiento

from .views import tendencias_tratamientos, backup_db, tendencias_generales_enfermedades

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', inicio, name='inicio'),
    path('api/citas/', todas_las_citas_json, name='todas_las_citas_json'),
    path('reporte/', generar_reporte, name='generar_reporte'),

    path('historial_paciente/<str:username>/', historial_paciente, name='historial_paciente'),
    path('tipo_citas/<str:tipo>/', tipo_citas_all, name='tipo_citas'),
    path('cantidad_total_citas/', cantidad_total_citas, name='cantidad_total_citas'),
    path('visualizacion/', visualizacion, name='visualizacion'),
    
    path('citas_asistio/', citas_asistio, name='citas_asistio'),
    path('citas_asistio/<str:fecha_inicio>/<str:fecha_fin>/', citas_asistio, name='citas_asistio_rango'),

    path('citas_no_asistio/', citas_no_asistio, name='citas_no_asistio'),
    path('citas_no_asistio/<str:fecha_inicio>/<str:fecha_fin>/', citas_no_asistio, name='citas_no_asistio_rango'),

    path('citas_pendientes/', citas_pendientes, name='citas_pendientes'),
    path('citas_pendientes/<str:fecha_inicio>/<str:fecha_fin>/', citas_pendientes, name='citas_pendientes_rango'),

    path('filtro_enfermedades/', filtro_enfermedades, name='filtro_enfermedades'),

    path('filtrar_registros_tratamientos/', filtrar_registros_tratamientos, name='filtrar_registros_tratamientos'),

    path('citas_visualizacion/', citas_visualizacion, name='citas_visualizacion'),

    path('doctores_all/', doctores_all, name='doctores_all'),

    path('enfermedades_cantidad_pacientes/', enfermedades_cantidad_pacientes, name='enfermedades_cantidad_pacientes'),

    path('buscar-pacientes2/', buscar_pacientes2, name='buscar_pacientes2'),

    path('datos_tendencias_enfermedades/', datos_tendencias_enfermedades, name='datos_tendencias_enfermedades'),

    path('estadisticas-tratamientos/', estadisticas_tratamientos, name='estadisticas_tratamientos'),

    path('enfermedades-por-tratamiento/', enfermedades_por_tratamiento, name='enfermedades_por_tratamiento'),

    path('tendencias-tratamientos/', tendencias_tratamientos, name='tendencias_tratamientos'),

    path('backup/', backup_db, name='backup_db'),


    path('login/', login_usuario, name='login'),
    path('register/', register, name='register'),

    path('error/', vista_error, name='error'),

    #registrar paciente
    path('registrar_paciente/',registrar_paciente,name="registrar_pacientes"),

    #urls vistas paciente
    path('paciente_inicio/',paciente_inicio,name='inicio_pacientes'),
    path('paciente_citas/',paciente_citas,name='mis_citas'),
    path('paciente_historial',paciente_historial,name='historial_medico'),

    path('login/medico/', login_medico, name='login_medico'),
    path('login/paciente/', login_paciente, name='login_paciente'),
    path('logout/', logout_user, name='logout'),
    path('forgot-password-med/', forgot_password_medico, name='forgot_password_med'),
    path('validate-otp/', validate_otp, name='validate_otp'),
    path('change-password/', change_password, name='change_password'),
    path('send-reminder/', send_reminder, name='send_reminder'),


    path('registrar/paciente/', registrar_paciente, name='registrar_paciente'),
    path('registrar/medico/', registrar_medico, name='registrar_medico'),

    path('dashboard/medico/', dashboard_medico, name='dashboard_medico'),
    path('dashboard/paciente/', dashboard_paciente, name='dashboard_paciente'),

    path('crear/alergia/', crear_alergia, name='crear_alergia'),
    path('listar/alergias/', listar_alergias, name='alergias'),
    path('crear/especialidad/', crear_especialidad, name='crear_especialidad'),

    
    path('medicos/', listar_medicos, name='doctores'),
    path('medicos/<int:medico_id>/', detalle_medico, name='detalle_medico'),
    path('medicos/<int:medico_id>/asignar-especialidad/', asignar_especialidad, name='asignar_especialidad'),

    path('enfermedades_alergias/', listar_enfermedades_alergias, name='enfermedades_alergias'),
    path('enfermedades/nuevo/', crear_enfermedad, name='crear_enfermedad'),
    path('tratamientos/', listar_tratamientos, name='tratamientos'),
    path('tratamientos/nuevo/', crear_tratamiento, name='crear_tratamiento'),
    path('tratamientos/asignar/', asignar_tratamiento, name='asignar_tratamiento'),

    path('enfermedades-tratamientos/', listar_enfermedades_tratamientos, name='listar_enfermedades_tratamientos'),


    path('agregar-producto/', agregar_producto, name='agregar_producto'),
    path('productos/', listar_productos, name='productos'),

    path('crear/cita/', crear_cita, name='crear_cita'),
    path('citas/', listar_citas, name='listar_citas'),
    path('citas/editar/', editar_cita, name='editar_cita'),
    path('validar-disponibilidad/', validar_disponibilidad_medico, name='validar_disponibilidad'),


    path('buscar_pacientes/', buscar_pacientes, name='buscar_pacientes'),
    path('buscar_medicos/', buscar_medicos, name='buscar_medicos'),
    path('buscar_cita/', buscar_cita, name='buscar_cita'),

    path('buscar-enfermedades/', buscar_enfermedades, name='buscar_enfermedades'),

    path('crear/registro/', crear_registro, name='crear_registro'),

    path('tratamientos-por-enfermedad/', tratamientos_por_enfermedad, name='tratamientos_por_enfermedad'),

    path('obtener_especialidades/', obtener_especialidades, name='obtener_especialidades'),

    path("tendencias_generales_enfermedades/", tendencias_generales_enfermedades, name="tendencias_generales_enfermedades"),
]

BackEnd/sagrado_corazon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('citas.urls')),
]

BackEnd/citas/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.core.exceptions import ValidationError

class Usuario(AbstractUser):
    ROLE_CHOICES = [
        ('Paciente', 'Paciente'),
        ('Medico', 'Medico'),
    ]
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, null=True, blank=True)
    genero = models.CharField(max_length=10, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], null=True, blank=True)

    groups = models.ManyToManyField(
        Group,
        related_name="customuser_set",  # Cambiar el nombre para evitar conflicto
        blank=True
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name="customuser_permissions",  # Cambiar el nombre para evitar conflicto
        blank=True
    )

    def clean(self):
        if self.role not in dict(self.ROLE_CHOICES):
            raise ValidationError("Rol inválido.")

    def __str__(self):
        return self.username

class Paciente(models.Model):
    user = models.OneToOneField(Usuario, on_delete=models.CASCADE, related_name='paciente_profile')
    genero = models.CharField(max_length=200, null=True, blank=True)
    direccion = models.TextField(default='')  # Asignar un valor predeterminado para evitar el error
    motivo = models.TextField(null=True, blank=True)
    cedula = models.CharField(max_length=20)
    telefono = models.CharField(max_length=20, blank=True, null=True)
    fecha_nacimiento = models.DateField()
    enfermedadess = models.JSONField(null=True, blank=True)
    alergiass = models.JSONField(null=True, blank=True)
    contacto_emergencias = models.CharField(max_length=200, null=True)
    telefono_emergencia = models.CharField(max_length=20, blank=True, null=True)
    apellido = models.CharField(max_length=100, default='Desconocido')  # Asignamos un valor predeterminado

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

class Medico(models.Model):
    user = models.OneToOneField(Usuario, on_delete=models.CASCADE, related_name='medico_profile')
    telefono = models.CharField(max_length=15, blank=True, null=True)
    es_admin = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

class Alergia(models.Model):
    codigo = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nombre

class PacienteAlergia(models.Model):
    id_paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, related_name='alergias')
    codigo = models.ForeignKey(Alergia, on_delete=models.CASCADE, related_name='pacientes')

    class Meta:
        unique_together = ('id_paciente', 'codigo')

    def __str__(self):
        return f"{self.id_paciente} - {self.codigo}"

class Especialidad(models.Model):
    id_especialidad = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class MedicoEspecialidad(models.Model):
    id_medico = models.ForeignKey(Medico, on_delete=models.CASCADE)
    id_especialidad = models.ForeignKey(Especialidad, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('id_medico', 'id_especialidad')

    def __str__(self):
        return f"{self.id_medico} - {self.id_especialidad}"

class Cita(models.Model):
    PENDIENTE = 'pendiente'
    FINALIZADA = 'finalizada'
    NO_ASISTIO = 'no_asistio'
    ELIMINADA = 'eliminada'

    ESTADO_CHOICES = [
        (PENDIENTE, 'Pendiente'),
        (FINALIZADA, 'Finalizada'),
        (NO_ASISTIO, 'No asistió'),
        (ELIMINADA, 'Eliminada'),
    ]
    
    id_cita = models.AutoField(primary_key=True)
    id_paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    id_medico = models.ForeignKey(Medico, on_delete=models.CASCADE)
    id_especialidad = models.ForeignKey(Especialidad, on_delete=models.CASCADE)
    fecha = models.DateField()
    hora = models.TimeField()
    estado = models.CharField(max_length=15, choices=ESTADO_CHOICES, default=PENDIENTE)

    def __str__(self):
        return f"{self.id_paciente} - {self.id_medico} - {self.fecha} - {self.hora}"
    
class Enfermedad(models.Model):
    id_enfermedad = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nombre

class PacienteEnfermedad(models.Model):
    id_paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    id_enfermedad = models.ForeignKey(Enfermedad, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('id_paciente', 'id_enfermedad')

    def __str__(self):
        return f"{self.id_paciente} - {self.id_enfermedad}"

class Registro(models.Model):
    id_registro = models.AutoField(primary_key=True)
    motivo = models.TextField()
    observaciones = models.TextField()
    id_cita = models.ForeignKey(Cita, on_delete=models.CASCADE)
    id_enfermedad = models.ForeignKey(Enfermedad, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.id_registro} - {self.id_enfermedad}"

class Tratamiento(models.Model):
    id_tratamiento = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nombre

class TratamientoEnfermedad(models.Model):
    id_tratamiento = models.ForeignKey(Tratamiento, on_delete=models.CASCADE)
    id_enfermedad = models.ForeignKey(Enfermedad, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('id_tratamiento', 'id_enfermedad')

    def __str__(self):
        return f"{self.id_tratamiento} - {self.id_enfermedad}"
    
class RegistroTratamiento(models.Model):
    id_registro = models.ForeignKey(Registro, on_delete=models.CASCADE, related_name="tratamientos")
    id_tratamiento = models.ForeignKey(Tratamiento, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('id_registro', 'id_tratamiento')

    def __str__(self):
        return f"Registro {self.id_registro.id_registro} - Tratamiento {self.id_tratamiento.nombre}"

class Producto(models.Model):
    id_producto = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    marca = models.CharField(max_length=100)
    tipo = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class RegistroProducto(models.Model):
    id_registro = models.ForeignKey(Registro, on_delete=models.CASCADE)
    id_producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('id_registro', 'id_producto')

    def __str__(self):
        return f"{self.id_registro} - {self.id_producto}"

BackEnd/citas/forms.py
from django import forms
from .models import Usuario, Paciente, Medico
from django.contrib.auth.models import User

class FormularioBusqueda(forms.Form):
    busqueda = forms.CharField(label='Busqueda', max_length=100)

class CustomUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True, label="Nombre")
    last_name = forms.CharField(max_length=30, required=True, label="Apellido")
    password1 = forms.CharField(widget=forms.PasswordInput, label="Contraseña")
    password2 = forms.CharField(widget=forms.PasswordInput, label="Confirmar contraseña")

    class Meta:
        model = Usuario
        fields = ['username', 'email', 'first_name', 'last_name' ,'role', 'genero', 'password1', 'password2']
    
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return password2

class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = ['cedula', 'telefono', 'fecha_nacimiento']

class MedicoForm(forms.ModelForm):
    class Meta:
        model = Medico
        fields = ['telefono']

class UploadExcelForm(forms.Form):
    excel_file = forms.FileField(
        label='Selecciona archivo Excel',
        help_text='Formatos soportados: .xlsx, .xls',
        widget=forms.FileInput(attrs={
            'accept': '.xlsx,.xls',
            'class': 'form-control-file'
        })
    )

BackEnd/citas/templates/citas2/medicos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Doctores</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/medicos.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <script src="{% static 'js/pagination.js' %}" defer></script>
    <link rel="icon" href="{% static 'imagenes/logo_ICO.ico' %}" type="image/x-icon" />
</head>
<body>
    <main class="main-body">
        <div class="sidebar">
            <div class="logo-container">
                <img src="{% static 'imagenes/logo_derma.png' %}" alt="Logo DermaCare" class="logo-img">
            </div>
            <nav>
                <a href="{% url 'inicio' %}" class="nav-item">
                    <i class="fas fa-home icon"></i> Inicio
                </a>
                <a href="{% url 'doctores' %}" class="nav-item active">
                    <i class="fas fa-user-md icon"></i> Doctores
                </a>
                <a href="{% url 'registrar_pacientes' %}" class="nav-item">
                    <i class="fas fa-procedures icon"></i> Pacientes
                </a>
                <a href="{% url 'productos' %}" class="nav-item">
                    <i class="fas fa-pills icon"></i> Productos
                </a>
                <a href="{% url 'enfermedades_alergias' %}" class="nav-item">
                    <i class="fas fa-allergies icon"></i> Alergias y Enfermedades
                </a>
                <a href="{% url 'tratamientos' %}" class="nav-item">
                    <i class="fas fa-heartbeat icon"></i> Tratamientos
                </a>
                <a href="{% url 'visualizacion' %}" class="nav-item">
                    <i class="fas fa-chart-line icon"></i> Visualización
                </a>
            </nav>
        </div>
        <div class="main-content">
            <div class="top-bar">
                <h2>Doctores</h2>
                
            </div>
            
            <div class="container-fluid px-0">
    <div class="row g-3 align-items-center mb-3">
        <div class="col-auto">
            <button class="btn btn-primary" id="agregarDoctorBtn" data-bs-toggle="modal" data-bs-target="#agregarDoctorModal">Agregar Médico</button>
        </div>
    </div>

    {% if messages %}
        <div class="container mt-3">
        {% for message in messages %}
        <div
            class="alert alert-success alert-dismissible fade show"
            role="alert"
        >
            <strong>{{ message }}</strong>
            <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
            ></button>
        </div>
        {% endfor %}
        </div>
    {% endif %}

            <div id="items" class="dc-row">
                {% for doctor in medicos %}
                <div class="dc-col">
                    <div class="dc-product-card">
                        <div class="dc-card-img-container">
                            {% if doctor.foto %}
                                <img src="{{ doctor.foto.url }}" class="dc-card-img" alt="{{ doctor.nombre }}">
                            {% else %}
                                <div class="dc-default-icon">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#5d9cec">
                                        <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 3c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zm0 14.2c-2.5 0-4.71-1.28-6-3.22.03-1.99 4-3.08 6-3.08 1.99 0 5.97 1.09 6 3.08-1.29 1.94-3.5 3.22-6 3.22z"/>
                                    </svg>
                                </div>
                            {% endif %}
                        </div>
                        <div class="dc-card-body">
                            <h5 class="dc-card-title">{{ doctor }}</h5>
                            <p class="dc-card-text">
                                <strong>Especialidades:</strong>
                                <ul class="dc-specialties-list">
                                    {% for especialidad in doctor.medicoespecialidad_set.all %}
                                        <li>{{ especialidad.id_especialidad.nombre }}</li>
                                    {% endfor %}
                                </ul>
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            
            <!-- Controles de paginación -->
            <div id="paginationControls" class="mt-3 d-flex justify-content-center"></div>
            </div>
        </div>

        <!-- Modal para perfil doctores -->
        <div class="modal fade" id="perfilDoctorModal" tabindex="-1" aria-labelledby="perfilDoctorModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="perfilDoctorModalLabel">Perfil del Doctor</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                    </div>
                    <div class="modal-body text-center">
                        <img id="fotoDoctor" src="" alt="Foto del Doctor" class="rounded-circle mb-3" style="width: 120px; height: 120px; object-fit: cover;">
                        <h5 id="nombreDoctor" class="mb-2"></h5>
                        <p id="generoDoctor" class="mb-1 text-muted"></p>
                        <p id="especialidadDoctor" class="fw-bold"></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal para agregar doctores -->
        <div class="modal fade" id="agregarDoctorModal" tabindex="-1" aria-labelledby="agregarDoctorModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="agregarDoctorModalLabel">Agregar Doctor</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" action="{% url 'registrar_medico' %}">
                            {% csrf_token %}
                            <!-- Usuario -->
                            <div class="mb-3">
                                <label for="username" class="form-label">Usuario</label>
                                <input type="text" class="form-control" id="username" name="username" placeholder="Ingrese el nombre de usuario">
                            </div>
                            <!-- Email -->
                            <div class="mb-3">
                                <label for="email" class="form-label">Correo Electrónico</label>
                                <input type="email" class="form-control" id="email" name="email" placeholder="Ingrese el correo electrónico">
                            </div>
                            <!-- Contraseña -->
                            <div class="mb-3">
                                <label for="password" class="form-label">Contraseña</label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="Ingrese la contraseña">
                            </div>
                            <!-- Nombre -->
                            <div class="mb-3">
                                <label for="first_name" class="form-label">Nombre</label>
                                <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Ingrese el nombre">
                            </div>
                            <!-- Apellido -->
                            <div class="mb-3">
                                <label for="last_name" class="form-label">Apellido</label>
                                <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Ingrese el apellido">
                            </div>
                            <!-- Género -->
                            <div class="mb-3">
                                <label for="genero" class="form-label">Género</label>
                                <select class="form-control" id="genero" name="genero">
                                    <option value="Masculino">Masculino</option>
                                    <option value="Femenino">Femenino</option>
                                    <option value="Otro">Otro</option>
                                </select>
                            </div>
                            <!-- Teléfono -->
                            <div class="mb-3">
                                <label for="telefono" class="form-label">Teléfono</label>
                                <input type="tel" class="form-control" id="telefono" name="telefono" placeholder="Ingrese el número de teléfono">
                            </div>
                            <!-- Especialidades -->
                            <div class="mb-3">
                                <label class="form-label">Especialidades</label>
                                <div>
                                    {% for especialidad in especialidades %}
                                    <div class="form-check">
                                        <input
                                            class="form-check-input"
                                            type="checkbox"
                                            id="especialidad_{{ especialidad.id_especialidad }}"
                                            name="especialidades"
                                            value="{{ especialidad.id_especialidad }}"
                                        >
                                        <label class="form-check-label" for="especialidad_{{ especialidad.id_especialidad }}">
                                            {{ especialidad.nombre }}
                                        </label>
                                    </div>
                                    {% endfor %}
                                </div>
                                <!-- Es admin -->
                                <div class="mb-3">
                                    <label for="is_admin" class="form-label">¿Es administrador?</label>
                                    <select class="form-control" id="is_admin" name="is_admin">
                                        <option value="False" selected>No</option>
                                        <option value="True">Sí</option>
                                    </select>
                                </div>
                            <!-- Botón -->
                            <button type="submit" class="btn btn-success">Agregar Doctor</button>
                        </form>
                    </div>
                    
                </div>
            </div>
        </div>
    </main>
    <script src="{% static 'js/perfil-doctor.js' %}"></script>
    <script src="{% static 'js/especialidades.js' %}"></script>
</body>
</html>

BackEnd/citas/templates/citas2/vista_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" href="{% static 'imagenes/logo_ICO.ico' %}" type="image/x-icon" />
</head>
<body>
    <div class="container mt-5">
        <!-- Alerta de error -->
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Advertencia:</strong> No tienes permiso para acceder.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Cerrar"></button>
        </div>
        <!-- Mensaje principal -->
        <div class="text-center mt-4">
            <h1 class="text-danger">Acceso denegado</h1>
            <p class="text-muted">Por favor, verifica tus permisos o contacta al administrador.</p>
            <a href="/" class="btn btn-primary">Volver al inicio</a>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>